version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: flowise
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flowise:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - IFRAME_ORIGINS=${IFRAME_ORIGINS}
      - FLOWISE_USERNAME=${FLOWISE_USERNAME}
      - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
      - FLOWISE_FILE_SIZE_LIMIT=${FLOWISE_FILE_SIZE_LIMIT}
      - DEBUG=${DEBUG}
      - DATABASE_TYPE=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=flowise
      - DATABASE_USER=root
      - DATABASE_PASSWORD=mypassword
      - DATABASE_SSL=false
      - APIKEY_STORAGE_TYPE=${APIKEY_STORAGE_TYPE}
      - APIKEY_PATH=${APIKEY_PATH}
      - SECRETKEY_PATH=${SECRETKEY_PATH}
      - FLOWISE_SECRETKEY_OVERWRITE=${FLOWISE_SECRETKEY_OVERWRITE}
      # - LOG_LEVEL=${LOG_LEVEL}
      # - LOG_PATH=${LOG_PATH}
      # - BLOB_STORAGE_PATH=${BLOB_STORAGE_PATH}
      # - DISABLE_FLOWISE_TELEMETRY=${DISABLE_FLOWISE_TELEMETRY}
      # - MODEL_LIST_CONFIG_JSON=${MODEL_LIST_CONFIG_JSON}
      # - GLOBAL_AGENT_HTTP_PROXY=${GLOBAL_AGENT_HTTP_PROXY}
      # - GLOBAL_AGENT_HTTPS_PROXY=${GLOBAL_AGENT_HTTPS_PROXY}
      # - GLOBAL_AGENT_NO_PROXY=${GLOBAL_AGENT_NO_PROXY}
      # - DISABLED_NODES=${DISABLED_NODES}
      # - MODE=${MODE}
      # - WORKER_CONCURRENCY=${WORKER_CONCURRENCY}
      # - QUEUE_NAME=${QUEUE_NAME}
      # - QUEUE_REDIS_EVENT_STREAM_MAX_LEN=${QUEUE_REDIS_EVENT_STREAM_MAX_LEN}
      # - REDIS_URL=${REDIS_URL}
      # - REDIS_HOST=${REDIS_HOST}
      # - REDIS_PORT=${REDIS_PORT}
      # - REDIS_PASSWORD=${REDIS_PASSWORD}
      # - REDIS_USERNAME=${REDIS_USERNAME}
      # - REDIS_TLS=${REDIS_TLS}
      # - REDIS_CERT=${REDIS_CERT}
      # - REDIS_KEY=${REDIS_KEY}
      # - REDIS_CA=${REDIS_CA}
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ~/.flowise:/root/.flowise
    working_dir: /usr/src
    entrypoint: /bin/sh -c "sleep 2; pnpm start"

volumes:
  postgres_data:
