name: CI
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - run: npx nx-cloud start-ci-run --distribute-on="3 linux-large-js" --agents

      - run: npm ci

      - uses: nrwl/nx-set-shas@v4

      - run: npx nx affected --target=lint --agents
      - run: npx nx affected --target=build -c production --agents
      - run: npx nx run-many --target=test --projects=engine,shared,server-api --agents
