version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.local
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_NAME=noyco
      - DB_PASS=postgres
      - DB_PORT=5432
      - JWT_SECRET=noyco-workflow-builder
      - NODE_ENV=development
    volumes:
      - .:/src/app
      - /src/app/node_modules
    command: ["npm", "run", "dev"]
